"""Verify the sniff / auth-trace decoder against a synthetic real trace.

firmware/components/chameleon/src/sniff_decoder.cpp turns the packed frame buffer
from HF14A_SNIFF / HF14A_AUTH_TRACE into Crypto1 authentication records. Getting
it wrong is silent: a mis-read offset yields plausible looking nonces that no
crack can ever use.

So the trace is built the way the firmware builds it, from a real authentication
generated by the reference crypto1.py, and the decoder has to hand back exactly
the nonces that went in.

Frame layout taken from app_cmd.c cmd_processor_hf14a_auth_trace:
  reader->card  4 bytes  AUTH cmd: 0x60/0x61, block, CRC[2]
  card->reader  4 bytes  nt (plaintext)
  reader->card  8 bytes  nr_enc[4] || ar_enc[4]
  card->reader  4 bytes  the card's encrypted answer
plus the synthesised anticoll frames the handler writes before the auth.

Usage:  python tools/verify_sniff_decoder.py
"""

import importlib.util
import os
import subprocess
import sys
import tempfile
from pathlib import Path

# Where the reference ChameleonUltra checkout lives. The probes compare the port
# against upstream sources, so point this at your own checkout of
# https://github.com/chameleonultra/ChameleonUltra if it is somewhere else:
#     $env:CU_UPSTREAM = "D:\src\ChameleonUltra"
CU_UPSTREAM = Path(os.environ.get("CU_UPSTREAM", r"C:\Users\Jiang\Downloads\ChameleonUltra-main"))
# The probes compare against upstream sources; without them there is nothing to
# compare, so refuse to run rather than report a comparison of nothing.
_UPSTREAM_SENTINEL = CU_UPSTREAM / "software" / "script" / "chameleon_cmd.py"
if not _UPSTREAM_SENTINEL.is_file():
    raise SystemExit(
        f"upstream ChameleonUltra checkout not found at {CU_UPSTREAM}\n"
        f"  (looked for {_UPSTREAM_SENTINEL})\n"
        "set CU_UPSTREAM to your checkout of "
        "https://github.com/RfidResearchGroup/ChameleonUltra"
    )



REPO = Path(__file__).resolve().parent.parent
CHAM = REPO / "firmware" / "components" / "chameleon"
SCRIPT_DIR = CU_UPSTREAM / "software" / "script"
GCC = Path(r"C:\mingw64\bin\g++.exe")

HARNESS = r"""
#include <inttypes.h>
#include <stdio.h>
#include <string.h>
#include "sniff_decoder.h"

using namespace chameleon;

/* frames <hex> : print every decoded frame */
static int cmd_frames(int argc, char** argv) {
    if (argc < 2) return 2;
    uint8_t buf[8192];
    size_t n = 0;
    for (size_t k = 0; argv[1][k] && argv[1][k + 1] && n < sizeof(buf); k += 2) {
        unsigned v = 0;
        if (sscanf(argv[1] + k, "%2x", &v) != 1) break;
        buf[n++] = (uint8_t)v;
    }

    TraceFrame frames[64];
    const size_t count = DecodeTraceFrames(buf, n, frames, 64);
    printf("frames %zu\n", count);
    for (size_t i = 0; i < count; ++i) {
        printf("  %zu %s bits=%zu bytes=%zu:", i, frames[i].from_card ? "card->reader" : "reader->card",
               frames[i].bit_length, frames[i].byte_length);
        for (size_t k = 0; k < frames[i].byte_length; ++k) printf(" %02X", frames[i].data[k]);
        printf("\n");
    }

    TraceAuth auths[8];
    const size_t auth_count = DecodeTraceAuths(buf, n, auths, 8);
    printf("auths %zu\n", auth_count);
    for (size_t i = 0; i < auth_count; ++i) {
        printf("  %zu block=%u type=%02X nt=%08" PRIX32 " nr=%08" PRIX32 " ar=%08" PRIX32 " complete=%d\n", i,
               (unsigned)auths[i].block, (unsigned)auths[i].key_type, auths[i].nt, auths[i].nr_enc, auths[i].ar_enc,
               auths[i].complete ? 1 : 0);
    }
    return 0;
}

int main(int argc, char** argv) {
    if (argc < 3) return 2;
    if (strcmp(argv[1], "frames") == 0) return cmd_frames(argc - 1, argv + 1);
    return 2;
}
"""


def load_reference():
    sys.path.insert(0, str(SCRIPT_DIR))
    spec = importlib.util.spec_from_file_location("crypto1", SCRIPT_DIR / "crypto1.py")
    mod = importlib.util.module_from_spec(spec)
    sys.modules["crypto1"] = mod
    spec.loader.exec_module(mod)
    return mod.Crypto1


def push_frame(out, data, bits, from_card):
    """Mirror auth_trace_store(): big-endian bit count, bit 15 = card -> reader."""
    header = bits | (0x8000 if from_card else 0)
    out += bytes([(header >> 8) & 0xFF, header & 0xFF])
    out += bytes(data[: (bits + 7) // 8])


def main():
    Crypto1 = load_reference()

    uid = 0x65535D33
    key_hex = "ffffffffffff"
    key64 = int(key_hex, 16)

    # A real authentication, as the reference implementation defines it.
    nt = 0xBE2B7B5D
    nr_plain = Crypto1.prng_next(nt, 32)
    st = Crypto1()
    st.key = key_hex
    st.lfsr48_u32(uid ^ nt, False)          # ks0
    ks1 = st.lfsr48_u32(nr_plain, False)    # ks1
    ks2 = st.lfsr48_u32(0, False)           # ks2
    nr_enc = nr_plain ^ ks1
    ar = Crypto1.prng_next(nt, 64)
    ar_enc = ar ^ ks2

    # The trace: a bit of anticoll first (a 7 bit REQA, so the decoder must walk
    # bit counts rather than assume byte alignment), then the four auth frames.
    trace = bytearray()
    push_frame(trace, [0x26], 7, False)                    # REQA, reader -> card
    push_frame(trace, [0x04, 0x40], 16, True)              # ATQA
    push_frame(trace, [0x93, 0x20], 16, False)             # anticoll
    push_frame(trace, [0xDE, 0xAD, 0xBE, 0xEF], 32, True)  # UID (dummy)
    push_frame(trace, [0x60, 0x03, 0xAA, 0xBB], 32, False)  # AUTH key A, block 3, CRC
    push_frame(trace, list(nt.to_bytes(4, "big")), 32, True)
    push_frame(trace, list(nr_enc.to_bytes(4, "big")) + list(ar_enc.to_bytes(4, "big")), 64, False)
    push_frame(trace, list(ar_enc.to_bytes(4, "big")), 32, True)

    print(f"uid={uid:08X} nt={nt:08X} nr_plain={nr_plain:08X}")
    print(f"expected: nr_enc={nr_enc:08X} ar_enc={ar_enc:08X} (ar={ar:08X})")

    # Sanity: the reference itself must accept this as a reader-has-key trace.
    oracle = Crypto1.mfkey32_is_reader_has_key(uid, nt, nr_enc, ar_enc, key_hex)
    print(f"reference oracle accepts the trace: {oracle}")

    failures = []

    def check(label, ok, detail=""):
        if ok:
            print(f"  ok   {label}")
        else:
            print(f"  FAIL {label}  {detail}")
            failures.append(label)

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        src = tmp / "decoder_harness.cpp"
        src.write_text(HARNESS, encoding="utf-8")
        exe = tmp / "decoder_harness.exe"
        cmd = [
            str(GCC), "-std=gnu++17", "-O1", "-w",
            "-I", str(CHAM / "include"),
            str(src),
            str(CHAM / "src" / "sniff_decoder.cpp"),
            "-o", str(exe),
        ]
        res = subprocess.run(cmd, capture_output=True, text=True)
        if res.returncode != 0:
            print("harness build failed:\n", res.stdout[-3000:], res.stderr[-3000:])
            return 1

        out = subprocess.run([str(exe), "frames", trace.hex()], capture_output=True, text=True).stdout
        print("\n" + out.rstrip())

        check("decoder found 8 frames", "frames 8" in out, out.splitlines()[0] if out else "")
        check("decoder found exactly one authentication", "auths 1" in out, "")

        line = next((l for l in out.splitlines() if "block=" in l), "")
        check(f"block number is 3", "block=3" in line, line)
        check("key type is 0x60 (key A)", "type=60" in line, line)
        check(f"nt matches ({nt:08X})", f"nt={nt:08X}" in line, line)
        check(f"nr_enc matches ({nr_enc:08X})", f"nr={nr_enc:08X}" in line, line)
        check(f"ar_enc matches ({ar_enc:08X})", f"ar={ar_enc:08X}" in line, line)
        check("authentication reported complete", "complete=1" in line, line)

        # A trace cut short (the device stores partial traces when the card
        # rejects the key) must be reported as an *incomplete* authentication:
        # distinguishable from "no authentication at all", and unusable as attack
        # material either way.
        truncated = trace[: len(trace) - 6]
        out2 = subprocess.run([str(exe), "frames", truncated.hex()], capture_output=True, text=True).stdout
        check("a truncated trace still reports the authentication it started",
              "auths 1" in out2, out2.replace("\n", " | ")[-200:])
        check("but marks it incomplete",
              "complete=0" in out2, out2.replace("\n", " | ")[-200:])

        # A trace with no AUTH command at all is not an authentication.
        no_auth = bytearray()
        push_frame(no_auth, [0x26], 7, False)
        push_frame(no_auth, [0x04, 0x40], 16, True)
        out3 = subprocess.run([str(exe), "frames", no_auth.hex()], capture_output=True, text=True).stdout
        check("a trace without an AUTH command yields no authentication",
              "auths 0" in out3, out3.replace("\n", " | ")[-160:])

    print()
    if failures:
        print(f"{len(failures)} CHECK(S) FAILED:")
        for f in failures:
            print("  -", f)
        return 1
    print("ALL SNIFF DECODER CHECKS PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
